SELECT * FROM FORECAST.MAINT_FEE_EVENT a
WHERE a.ISSUE_DT > TO_DATE('10-01-1989', 'MM-DD-YYYY');

SELECT a.PATENT_NO FROM FORECAST.MAINT_FEE_EVENT a
WHERE a.ISSUE_DT > TO_DATE('10-01-1989', 'MM-DD-YYYY');

--Verifying number of patents granted similiar between data sets
SELECT EXTRACT(year from a.ISSUE_DT) "Year", COUNT(UNIQUE(a.PATENT_NO)) "Count"
FROM FORECAST.MAINT_FEE_EVENT a
WHERE a.ISSUE_DT > TO_DATE('10-01-1989', 'MM-DD-YYYY')
GROUP BY EXTRACT(year from a.ISSUE_DT)
ORDER BY EXTRACT(year from a.ISSUE_DT) DESC;

SELECT EXTRACT(year from a.ISS_DA) "Year", COUNT(UNIQUE(a.SER_NO)) "Count"
FROM DW.ALL_PAT_CASE a
WHERE a.INV_CD = 'UTL' 
AND a.ISS_DA > TO_DATE('09-30-1989', 'MM-DD-YYYY')
GROUP BY EXTRACT(year from a.ISS_DA)
ORDER BY EXTRACT(year from a.ISS_DA) DESC;

--Verifying patent types
SELECT a.INV_CD, COUNT(*)
FROM DW.ALL_PAT_CASE a
GROUP BY a.INV_CD;

SELECT * FROM DW.ALL_PAT_CASE a WHERE a.INV_CD IS NULL;

--counts for patents granted by year
SELECT EXTRACT(year from a.ISS_DA) "Year", COUNT(UNIQUE(a.SER_NO)) "Count"
FROM DW.ALL_PAT_CASE a 
LEFT JOIN FORECAST.MAINT_FEE_EVENT b
ON a.SER_NO = b.APPL_ID
WHERE a.INV_CD = 'UTL' 
AND a.ISS_DA > TO_DATE('09-30-1989', 'MM-DD-YYYY')
GROUP BY EXTRACT(year from a.ISS_DA)
ORDER BY EXTRACT(year from a.ISS_DA) DESC;

--Using Forecast.PAT_Case for consistency with Maintenance Fee Model
SELECT a.ISS_DA "Week", COUNT(UNIQUE(a.SER_NO)) "Patent_Count",
COUNT(CASE WHEN b.ENTRY_CD IN 
      ('M1551','M170','M173','M183','M2551','M273','M283','M3551') 
      THEN 1 ELSE NULL END) "1st_count",
COUNT(CASE WHEN b.ENTRY_CD IN 
      ('M1552','M171','M174','M184','M2552','M274','M284','M3552') 
      THEN 1 ELSE NULL END) "2nd_count",
COUNT(CASE WHEN b.ENTRY_CD IN 
      ('M1553','M172','M175','M185','M2553','M275','M285','M3553') 
      THEN 1 ELSE NULL END) "3rd_count"
FROM FORECAST.PAT_CASE a 
LEFT JOIN FORECAST.MAINT_FEE_EVENT b
ON a.SER_NO = b.APPL_ID
WHERE a.INV_CD = 'UTL' 
AND a.ISS_DA > TO_DATE('09-30-1989', 'MM-DD-YYYY')
AND a.Pat_No Not LIKE 'D%'
GROUP BY a.ISS_DA
ORDER BY a.ISS_DA DESC;

--Verify previous query
SELECT a.ISSUE_DT, COUNT(*)
FROM FORECAST.MAINT_FEE_EVENT a
WHERE a.ISSUE_DT > TO_DATE('10-01-1989', 'MM-DD-YYYY')
AND a.ENTRY_CD IN ('M1551','M170','M173','M183','M2551','M273','M283','M3551') 
GROUP BY a.ISSUE_DT
ORDER BY a.ISSUE_DT DESC;

--Calculate Renewal Rates
SELECT TRUNC(a.ISS_DA, 'MON') "Month_Patent_Granted", 
COUNT(UNIQUE(a.SER_NO)) "Patent_Count",
ROUND(COUNT(CASE WHEN b.ENTRY_CD IN 
      ('M1551','M170','M173','M183','M2551','M273','M283','M3551') 
      THEN 1 ELSE NULL END)/COUNT(UNIQUE(a.SER_NO)),4) "1st_renewal_rate",
ROUND(COUNT(CASE WHEN b.ENTRY_CD IN 
      ('M1552','M171','M174','M184','M2552','M274','M284','M3552') 
      THEN 1 ELSE NULL END)/COUNT(UNIQUE(a.SER_NO)),4) "2nd_renewal_rate",
ROUND(COUNT(CASE WHEN b.ENTRY_CD IN 
      ('M1553','M172','M175','M185','M2553','M275','M285','M3553') 
      THEN 1 ELSE NULL END)/COUNT(UNIQUE(a.SER_NO)),4) "3rd_renewal_rate"
FROM FORECAST.PAT_CASE a 
LEFT JOIN FORECAST.MAINT_FEE_EVENT b
ON a.SER_NO = b.APPL_ID
WHERE a.INV_CD = 'UTL' 
AND a.ISS_DA > TO_DATE('09-30-1989', 'MM-DD-YYYY')
AND a.Pat_No Not LIKE 'D%'
GROUP BY TRUNC(a.ISS_DA, 'MON')
ORDER BY TRUNC(a.ISS_DA, 'MON') DESC;