CREATE INDEX IDX_TLS207_PERS_APPLN_ID ON TLS207_PERS_APPLN
(APPLN_ID);

CREATE INDEX IDX_TLS207_PERS_APPLN_PID ON TLS207_PERS_APPLN
(PERSON_ID);

CREATE INDEX IDX_TLS209_APPL_IPC_CSYMBOL ON TLS209_APPLN_IPC
(IPC_CLASS_SYMBOL);

CREATE INDEX IDX_TLS221_INPADOC_PRS_CODEIN ON TLS221_INPADOC_PRS
(PRS_CODE, APPLN_ID);

CREATE INDEX IDX_TLS221_INPADOC_PRS_GAZDAT ON TLS221_INPADOC_PRS
(PRS_GAZETTE_DATE, APPLN_ID);

CREATE INDEX IDX_TLS221_INPADOC_PRS_LECID ON TLS221_INPADOC_PRS
(LEC_ID, APPLN_ID);

CREATE INDEX IDX_TLS223_APPLN_DOCUS_SYMBOL ON TLS223_APPLN_DOCUS
(DOCUS_CLASS_SYMBOL);

CREATE UNIQUE INDEX TLS207_PK ON TLS207_PERS_APPLN
(PERSON_ID, APPLN_ID, APPLT_SEQ_NR, INVT_SEQ_NR);

CREATE UNIQUE INDEX TLS209_PK ON TLS209_APPLN_IPC
(APPLN_ID, IPC_CLASS_SYMBOL);

CREATE UNIQUE INDEX TLS221_PK ON TLS221_INPADOC_PRS
(APPLN_ID, PRS_EVENT_SEQ_NR);

CREATE UNIQUE INDEX TLS223_PK ON TLS223_APPLN_DOCUS
(APPLN_ID, DOCUS_CLASS_SYMBOL);

CREATE UNIQUE INDEX TLS224_PK ON TLS224_APPLN_CPC
(APPLN_ID, CPC_CLASS_SYMBOL, CPC_SCHEME);

CREATE UNIQUE INDEX TLS801_PK ON TLS801_COUNTRY
(CTRY_CODE);

CREATE UNIQUE INDEX TLS802_PK ON TLS802_LEGAL_EVENT_CODE
(LEC_ID);

CREATE UNIQUE INDEX TLS906_PK ON TLS906_PERSON
(PERSON_ID);

CREATE INDEX IDX_TLS906_PERSON_CTY ON TLS906_PERSON
(PERSON_CTRY_CODE);


ALTER TABLE TLS207_PERS_APPLN ADD (
  PRIMARY KEY
  (PERSON_ID, APPLN_ID, APPLT_SEQ_NR, INVT_SEQ_NR)
  USING INDEX TLS207_PK);

ALTER TABLE TLS209_APPLN_IPC ADD (
  PRIMARY KEY
  (APPLN_ID, IPC_CLASS_SYMBOL)
  USING INDEX TLS209_PK);

ALTER TABLE TLS221_INPADOC_PRS ADD (
  PRIMARY KEY
  (APPLN_ID, PRS_EVENT_SEQ_NR)
  USING INDEX TLS221_PK);

ALTER TABLE TLS223_APPLN_DOCUS ADD (
  PRIMARY KEY
  (APPLN_ID, DOCUS_CLASS_SYMBOL)
  USING INDEX TLS223_PK);

ALTER TABLE TLS224_APPLN_CPC ADD (
  PRIMARY KEY
  (APPLN_ID, CPC_CLASS_SYMBOL, CPC_SCHEME)
  USING INDEX TLS224_PK);

ALTER TABLE TLS801_COUNTRY ADD (
  PRIMARY KEY
  (CTRY_CODE)
  USING INDEX TLS801_PK);

ALTER TABLE TLS802_LEGAL_EVENT_CODE ADD (
  PRIMARY KEY
  (LEC_ID)
  USING INDEX TLS802_PK);

ALTER TABLE TLS906_PERSON ADD (
  PRIMARY KEY
  (PERSON_ID)
  USING INDEX TLS906_PK);

COMMIT;
